import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import Navbar from "../components/Navbar";
import ConditionalAnimatedBackground from "../components/ConditionalAnimatedBackground";
import AppLoader from "../components/AppLoader";
import CrackleCursor from "../components/CrackleCursor";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Only show AnimatedBackground on pages that are NOT donor-form or recipient-form
  const pathname = typeof window !== 'undefined' ? window.location.pathname : '';
  const showAnimatedBg =
    !pathname.startsWith('/donor-form') && !pathname.startsWith('/recipient-form');
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppLoader>
          <CrackleCursor />
          <ConditionalAnimatedBackground />
          <Navbar />
          {children}
          <Footer />
        </AppLoader>
      </body>
    </html>
  );
}
